import streamlit as st
import pandas as pd
from fpdf import FPDF
import razorpay
from datetime import date

st.set_page_config(page_title="Valuify - Scenario War DCF", layout="wide")

# --- RAZORPAY INIT ---
try:
    client = razorpay.Client(auth=(st.secrets["RAZORPAY_KEY_ID"], st.secrets["RAZORPAY_KEY_SECRET"]))
    razorpay_ready = True
except:
    razorpay_ready = False

# --- PDF GENERATOR ---
def create_pdf(company, fv, cmp, rec):
    pdf = FPDF()
    pdf.add_page()
    
    # Use core font to avoid issues
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, f"Valuify - {company} Valuation Report", ln=True, align='C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(200, 10, f"Date: {date.today()}", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(200, 10, f"Fair Value: Rs.{fv:,.0f}", ln=True) # Used Rs. instead of ₹
    pdf.cell(200, 10, f"Current Market Price: Rs.{cmp:,.0f}", ln=True)
    pdf.cell(200, 10, f"Upside/Downside: {((fv-cmp)/cmp)*100:.1f}%", ln=True)
    pdf.cell(200, 10, f"Recommendation: {rec}", ln=True)
    pdf.ln(10)
    
    pdf.set_font("Arial", 'I', 9)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by Valuify AI for educational purposes only. This is not SEBI registered financial advice.")
    
    filename = f"{company}_Valuify_Report.pdf"
    pdf.output(filename)
    return filename

# --- MOCK DATA ---
data = {
    "Company": ["TCS", "WIPRO", "INFY"],
    "Revenue": [240000, 91000, 153000],
    "FCF_Margin": [0.22, 0.18, 0.24],
    "Analyst_Growth": [0.09, 0.09, 0.10]
}
df = pd.DataFrame(data)

# --- UI ---
st.title("💰 Valuify - Scenario War DCF")
st.caption("Compare YOUR view vs MARKET vs ANALYST. Find hidden gems.")

col1, col2 = st.columns([1, 2])

with col1:
    st.header("Inputs")
    company = st.selectbox("Select Company", df["Company"])
    cmp = st.number_input("Enter Current Market Price CMP", value=3950.00, step=10.0)
    selected_data = df[df["Company"] == company].iloc[0]

with col2:
    st.header("⚔️ Scenario War: Who is Right?")
    
    user_growth = st.slider("YOUR Growth View", 0.0, 0.25, 0.12, 0.01)
    market_growth = st.slider("MARKET Implied Growth", 0.0, 0.25, 0.11, 0.01)
    analyst_growth = st.slider("ANALYST Growth View", 0.0, 0.25, float(selected_data["Analyst_Growth"]), 0.01)
    
    if st.button("RUN SCENARIO WAR", type="primary"):
        revenue = selected_data["Revenue"]
        margin = selected_data["FCF_Margin"]
        wacc = 0.11
        
        def calc_fv(g):
            fcf = revenue * margin
            terminal_value = fcf * (1+g) / (wacc - g) if wacc > g else fcf*10
            fv = terminal_value / ((1+wacc)**5)
            return fv
        
        fv_user = calc_fv(user_growth)
        fv_market = calc_fv(market_growth)
        
        st.session_state.fv = fv_user # Save for PDF
        st.session_state.cmp = cmp
        
        upside = ((fv_user - cmp) / cmp) * 100
        st.session_state.upside = upside
        
        if upside > 20: rec = "BUY"
        elif upside < -20: rec = "SELL"
        else: rec = "HOLD"
        st.session_state.rec = rec
        
        st.metric("YOUR Fair Value", f"Rs.{fv_user:,.0f}")
        st.metric("MARKET Implied FV", f"Rs.{fv_market:,.0f}")
        st.success(f"Verdict: {rec} with {upside:.1f}% Upside")

# --- PRO FEATURE ---
st.divider()
st.subheader("📄 Pro Feature")

if razorpay_ready:
    if st.button(f"Download {company} Report PDF - Rs.499"):
        if "fv" in st.session_state and st.session_state.fv > 0:
            try:
                # Create order - this simulates payment
                order = client.order.create({"amount": 49900, "currency": "INR", "payment_capture": 1})
                st.info("Payment system ready. Generating report...")
                
                pdf_file = create_pdf(company, st.session_state.fv, st.session_state.cmp, st.session_state.rec)
                with open(pdf_file, "rb") as file:
                    st.download_button(
                        label="⬇️ Download Your Paid Report",
                        data=file,
                        file_name=pdf_file,
                        mime="application/pdf"
                    )
                st.success("Report Generated!")
            except Exception as e:
                st.error(f"Payment Error: {e}")
        else:
            st.warning("⚠️ Please click 'RUN SCENARIO WAR' first to generate a valuation")
else:
    st.error("Add Razorpay Keys in Settings > Secrets to enable this")

st.caption("Built with Valuify AI | For testing use Razorpay test card: 4111 1111 1111 1111")
